query GetMeetingTemplate($meetingTemplateId: ID) {
  meetingTemplate(id: $meetingTemplateId) {
    data {
      id
      attributes {
        initialLatitude
        initialLongitude
        initialZoom
        name
        description
        createdAt
        updatedAt
        publishedAt
        video {
          data {
            id
            attributes {
              url
            }
          }
        }
        timeline {
          ... on ComponentMeetingEvent {
            id
            eventType
            description
            startAt
            endAt
            meeting_place {
              data {
                id
                attributes {
                  name
                  fullAddress
                  latitude
                  longitude
                  images {
                    data {
                      id
                      attributes {
                        url
                      }
                    }
                  }
                  createdAt
                  updatedAt
                }
              }
            }
            videoTriggers {
              id
              event
              seconds
            }
          }
          ... on ComponentMeetingTransfer {
            id
            description
            startAt
            endAt
            origin {
              data {
                id
                attributes {
                  name
                  fullAddress
                  latitude
                  longitude
                  images {
                    data {
                      id
                      attributes {
                        url
                      }
                    }
                  }
                  createdAt
                  updatedAt
                }
              }
            }
            destination {
              data {
                attributes {
                  name
                  latitude
                  longitude
                }
              }
            }
          }
        }
      }
    }
  }
}